export type Type = {
	'body-xs-regular': string;
	'body-xs-medium': string;
	'body-xs-bold': string;
	'body-s-regular': string;
	'body-s-medium': string;
	'body-s-bold': string;
	'body-m-regular': string;
	'body-m-medium': string;
	'body-m-bold': string;
	'body-l-regular': string;
	'body-l-medium': string;
	'body-l-bold': string;
	'heading-s-bold': string;
	'heading-s-medium': string;
	'heading-m-bold': string;
	'heading-m-medium': string;
	'heading-l-bold': string;
	'heading-l-medium': string;
};
